# Generated by Django 5.2.6 on 2025-09-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='addresses_city_id_ee478a_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state'], name='addresses_state_i_346448_idx'),
        ),
    ]
