# Generated by Django 5.2.6 on 2025-09-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='order_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('pending', 'Pending')], db_index=True, default='active', help_text='Status of the record', max_length=10),
        ),
    ]
