# Generated by Django 5.2.6 on 2025-09-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_orderstatushistory_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_digital',
        ),
    ]
