# Generated by Django 5.2.6 on 2025-09-15 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_is_best_seller_product_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('pending', 'Pending')], db_index=True, default='active', help_text='Status of the record', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=1000)),
                ('sort_order', models.IntegerField(default=0)),
                ('subcategories', models.ManyToManyField(related_name='banners', to='product.subcategory')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'created_at'], name='product_ban_status_034029_idx'), models.Index(fields=['status', 'updated_on'], name='product_ban_status_5ce353_idx')],
            },
        ),
    ]
