# Generated by Django 5.2.6 on 2025-09-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_banner'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='brand',
            name='brands_slug_6a4b1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='categories_slug_b4303a_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_slug_5e91f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='subcategory',
            name='sub categor_slug_012041_idx',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='brands_name_c58671_idx'),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='slug',
        ),
    ]
