# Generated by Django 5.2.6 on 2025-10-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_brand_brands_slug_6a4b1c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
