# Generated by Django 5.2.6 on 2025-10-03 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='reviews/media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='product.review')),
            ],
            options={
                'db_table': 'review_media',
                'indexes': [models.Index(fields=['review'], name='review_medi_review__76a520_idx'), models.Index(fields=['media_type'], name='review_medi_media_t_b7b213_idx')],
            },
        ),
    ]
