# Generated by Django 5.2.6 on 2025-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfaq',
            name='is_home_page_related',
            field=models.BooleanField(default=False),
        ),
    ]
