# Generated by Django 5.2.6 on 2025-09-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_blogcomment_ip_address'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogcategory',
            name='blog_catego_slug_ca79bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_posts_slug_b4ca25_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogtag',
            name='blog_tags_slug_720acc_idx',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blogtag',
            name='slug',
        ),
    ]
