# Generated by Django 5.2.6 on 2025-10-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_blogcategory_blog_catego_slug_ca79bd_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
