# Generated by Django 5.2.6 on 2025-09-06 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('pending', 'Pending')], db_index=True, default='active', help_text='Status of the record', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('payment_success', 'Payment Success'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome Email'), ('newsletter', 'Newsletter')], max_length=30, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('pending', 'Pending')], db_index=True, default='active', help_text='Status of the record', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_inclusive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tax_rates',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('pending', 'Pending')], db_index=True, default='active', help_text='Status of the record', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_type', models.CharField(choices=[('hero', 'Hero Banner'), ('promotional', 'Promotional Banner'), ('category', 'Category Banner')], max_length=20)),
                ('image_url', models.URLField()),
                ('link_url', models.URLField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'banners',
                'indexes': [models.Index(fields=['banner_type', 'status'], name='banners_banner__b11f0a_idx'), models.Index(fields=['valid_from', 'valid_until'], name='banners_valid_f_004122_idx')],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('pending', 'Pending')], db_index=True, default='active', help_text='Status of the record', max_length=10)),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('phone_code', models.CharField(max_length=10)),
                ('capital', models.CharField(max_length=250)),
                ('currency', models.CharField(max_length=100)),
                ('currency_name', models.CharField(max_length=250)),
                ('time_zone', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'country',
                'indexes': [models.Index(fields=['name'], name='country_name_3bb090_idx'), models.Index(fields=['currency', 'currency_name'], name='country_currenc_de559f_idx')],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('pending', 'Pending')], db_index=True, default='active', help_text='Status of the record', max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_country', to='utils.country')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted'), ('draft', 'Draft'), ('pending', 'Pending')], db_index=True, default='active', help_text='Status of the record', max_length=10)),
                ('name', models.CharField(max_length=250)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_state', to='utils.state')),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name'], name='state_name_73f286_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='district_name_ab7297_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['latitude', 'longitude'], name='district_latitud_ffd3c4_idx'),
        ),
    ]
